### ISSUE TITLE
Multiple H1s when LSX is active.

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-banners#5]
When LSX Banners is active it replaces the archive-title with a banner which has the header in but doesn't remove it which causes 2 h1's being present on the site. 
![Capture](https://user-images.githubusercontent.com/35291167/61282909-7deec100-a7bc-11e9-8312-ab728c7efc8e.PNG)

**Comment by krugazul** [comment]
@jacquesvdhorst this was because the global header was not being disabled on these pages.   I have added in a filter to do so and tested.  Only 1 h1 is now showing - https://github.com/lightspeeddevelopment/lsx-banners/commit/c939a6af095c9aa872cf7aac2ca443172534c274#diff-a3254cb2510b6a98a8e5b5b597548471R376
