### ISSUE TITLE
Trying to save an image banner here for the category archive, it's not working, all the functionality for banners on a category still need to be tested.

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-banners#8]
**Describe the bug**
Trying to save an image banner here for the category archive, it's not working. No image is being saved on this banner pages.

**To Reproduce**
1. Go to edit a category
2. Click on Banner
3. Pick an image
4. Save
5. Notice how it does not save.

**Expected behavior**
The image should be saved and display as banner in the archive page.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3129483/70822490-727be200-1dbc-11ea-8d82-1b77bfa57f9a.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/212](https://www.bugherd.com/projects/97685/tasks/212)

**Comment by krugazul** [comment]
@ashleyshaw   Ive tested this, deactivated all plugins.  It seems to be the actual terms that are broken.   There are duplicate terms, with the same name and slug.   Which is why is fails to update the term.   

Have a look at the screenshot below,  you will see there are 2 of every [category](https://lsx-demo.lsdev.biz/wp-admin/edit-tags.php?taxonomy=category).  1 of them needs to be deleted.
![Screenshot 2020-03-24 at 09 03 54](https://user-images.githubusercontent.com/1805603/77397542-7dc4ad80-6dae-11ea-9bc9-c8504cb07fe6.png)

I deleted 1 of the alignment categories, and made sure all 4 posts were attached.   I then updated the banner image.  And it saved fine.

Frontend - [With Banner](https://lsx-demo.lsdev.biz/wp-admin/term.php?taxonomy=category&tag_ID=4&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dcategory)
Backend Banner field - [Showing save value](https://lsx-demo.lsdev.biz/wp-admin/term.php?taxonomy=category&tag_ID=4&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dcategory)
